"Shows how you might create a macro for the autogeneratd Jest rule"

load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def jest_test(name, tests, srcs, deps, jest_config, **kwargs):
    "A macro around the autogenerated jest_test rule"
    templated_args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
    ]
    templated_args.extend(["--config", "$(rootpath %s)" % jest_config])
    for test in tests:
        templated_args.extend(["--runTestsByPath", "$(rootpath %s)" % test])

    _jest_test(
        name = name,
        data = [jest_config] + tests + srcs + deps,
        templated_args = templated_args,
        **kwargs
    )
